### PR TITLE
Add ability to coexist with another websocket server

### PR DESCRIPTION
**Pull request by Goopil**
Hello @thetutlage,

This is a small merge request to allow a second websocket server to coexist with yours.

I know this is an edge case you probably wouldn't want to support but I sadly need this functionality in one of my project.

In this project, I use 2 ws servers, one for a spa and another for inter server communication.
The other server is sadly not written in nodejs thus I'm unable to use your front library.

The test are passing and you can find a working project example [there](https://github.com/Goopil/adonisjs-websocket-dual-ws-server-demo)

Its not really an inter server communication but an extends of your websocket example with the necessary modification to start both server.

It goes without saying that if this merge request is included, i would be glad to make the necessary change in your documentation.

As always thanks for your hard work and for providing such a fantastic tool !

### CODE REVIEW

**Comment by Goopil** [comment]
P.S. For the test i made a copy of your ws.spec.js with the necessary change and runned it locally. If you want i can include the file in the pull request.

**Comment by thetutlage** [comment]
I believe running multiple servers should be fine. Websocket doesn't block you from starting an independent server.

Can you share some code on what exactly you are trying to do and also what limitations you have hit

**Comment by Goopil** [comment]
Hi @thetutlage,
Yes starting multiple websocket server sharing the same http server is possible with [websockets/ws](https://github.com/websockets/ws) packages.

But the initialisation sequence is different when you start more than one. The problem lies in the upgrade request, as the http server does not know which server the upgrade request is addressed to.
This pr is based on what you can see in the ws library documentation.
and here, you can find the differences.
it goes from 

```js
const https = require('http');
const WebSocket = require('ws');

const server = new https.createServer();
const wss = new WebSocket.Server({ server });

wss.on('connection', function connection(ws) {
...
});

server.listen(8080);
```

to

```js
const http = require('http');
const WebSocket = require('ws');

const server = http.createServer();
const wss1 = new WebSocket.Server({ noServer: true });
const wss2 = new WebSocket.Server({ noServer: true });

wss1.on('connection', function connection(ws) {
  // ...
});

wss2.on('connection', function connection(ws) {
  // ...
});

server.on('upgrade', function upgrade(request, socket, head) {
  const pathname = url.parse(request.url).pathname;

  if (pathname === '/foo') {
    wss1.handleUpgrade(request, socket, head, function done(ws) {
      wss1.emit('connection', ws, request);
    });
  } else if (pathname === '/bar') {
    wss2.handleUpgrade(request, socket, head, function done(ws) {
      wss2.emit('connection', ws, request);
    });
  } else {
    socket.destroy();
  }
});

server.listen(8080);
```

As you can see you have to initialize the websocket with `noServer: true` in place of passing the http server directly and handle the upgrade Request outside of it.

I've tested to start a second websocket server without these changes but both websocket servers (yours and the second one) didn't work properly. 

Strangly enough using uws for the second server didn't pose any problem. But i would rather use the same library for both server.

**Comment by Goopil** [comment]
For the code example, sadly i can't share the whole project. As this is the company I'm working at property. but i have recreated a sample repo for you to see what i have in mind. [https://github.com/Goopil/adonisjs-websocket-dual-ws-server-demo](https://github.com/Goopil/adonisjs-websocket-dual-ws-server-demo)

Its really simple, just to illustrate the dual ws server start and the event propagation from the first to the second. Nothing fancy.

**Comment by Goopil** [comment]
Hello ! 

Any news on this pr ?

Do you have other questions or needs before merging it ?

thanks in advance !

best regards

**Pull request closed without merging**
